#+TITLE: Teaching

After my first lecture last year, I came to like teaching and I continue to give
lectures while working on my Ph.D. thesis.

* Object oriented programming
:PROPERTIES:
:CUSTOM_ID: teaching-oop
:END:

This year, I give practical classes of object oriented programming in Java at
the [[https://u-bordeaux.com][University of Bordeaux]].

All the information about the course and the teaching materials are available
online in French at [[http://www.reveillere.fr/L3POO/]].

* Introduction to C programming
:PROPERTIES:
:CUSTOM_ID: taching-bts
:END:

During the last year, I was teaching programming in C language at
[[https://lyceesaintefamille.com/][Lycée Sainte-Famille Saintonge]] in Bordeaux
to the students of /Brevet de technicien supérieur/ (BTS) senior technologist's
certificate in Computer science.

Given that it was the first year of the curriculum in this institution, I was
also brought to propose an education plan, prepare the courses as well as
exercices and exams. The coronavirus crisis made my work even more difficult as
most of the second semester's courses had to be done remotely.

The teaching materials, exercices, exam and project subjects are available
online in French at [[https://mfelsoci.gitlabpages.inria.fr/lectures/]].

#+INCLUDE: ./shared/setup.org
